[package]
name = "sidecar"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util = "0.3.31"
notify = "8.2.0"
tokio = { version = "1.48.0", features = ["full"] }
tokio-tungstenite = "0.28.0"
